import { Hackathon } from "@/types/hackathon";

export const hackathons: Hackathon[] = [
  {
    id: "1",
    name: "AI Hack Tokyo",
    description: "AIを使ったプロダクト開発ハッカソン",
    location: "Tokyo",
    date: "2026-04-10",
    tags: ["AI", "Web"],
    level: "Intermediate",
    participationType: "Team",
    mode: "Offline",
  },
  {
    id: "2",
    name: "Web3 Global Online",
    description: "Web3特化のオンラインハッカソン",
    location: "Online",
    date: "2026-05-01",
    tags: ["Web3", "Blockchain"],
    level: "Beginner",
    participationType: "Solo",
    mode: "Online",
  },
  {
    id: "3",
    name: "Data Science Challenge",
    description: "データ分析と機械学習をテーマにしたハッカソン",
    location: "New York",
    date: "2026-05-20",
    tags: ["Data", "Machine Learning"],
    level: "Intermediate",
    participationType: "Team",
    mode: "Offline",
  },
  {
    id: "4",
    name: "Mobile App Builder",
    description: "スマホアプリ開発に挑戦するハッカソン",
    location: "Seoul",
    date: "2026-06-05",
    tags: ["Mobile", "App"],
    level: "Beginner",
    participationType: "Solo",
    mode: "Offline",
  },
  {
    id: "5",
    name: "Cyber Security Hack",
    description: "セキュリティ技術を競うハッカソン",
    location: "San Francisco",
    date: "2026-06-18",
    tags: ["Security", "Networking"],
    level: "Advanced",
    participationType: "Team",
    mode: "Offline",
  },
  {
    id: "6",
    name: "Open Source Sprint",
    description: "オープンソースプロジェクトを開発するイベント",
    location: "Berlin",
    date: "2026-07-02",
    tags: ["Open Source", "Web"],
    level: "Beginner",
    participationType: "Team",
    mode: "Online",
  },
  {
    id: "7",
    name: "Game Dev Jam",
    description: "ゲーム開発をテーマにしたハッカソン",
    location: "Los Angeles",
    date: "2026-07-15",
    tags: ["Game", "Unity"],
    level: "Beginner",
    participationType: "Team",
    mode: "Offline",
  },
  {
    id: "8",
    name: "FinTech Innovation",
    description: "金融テクノロジーをテーマにしたハッカソン",
    location: "London",
    date: "2026-08-01",
    tags: ["FinTech", "AI"],
    level: "Intermediate",
    participationType: "Team",
    mode: "Offline",
  },
  {
    id: "9",
    name: "Climate Tech Hack",
    description: "環境問題をテクノロジーで解決するハッカソン",
    location: "Amsterdam",
    date: "2026-08-20",
    tags: ["Climate", "AI"],
    level: "Intermediate",
    participationType: "Team",
    mode: "Online",
  },
  {
    id: "10",
    name: "Startup Builder Weekend",
    description: "スタートアップアイデアを形にするハッカソン",
    location: "Tokyo",
    date: "2026-09-05",
    tags: ["Startup", "Web"],
    level: "Advanced",
    participationType: "Team",
    mode: "Offline",
  },
];
